CREATE TABLE usuario
(
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario    VARCHAR(255)                            NOT NULL,
    senha      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario)
);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_usuario UNIQUE (usuario);
