CREATE TABLE profissional
(
    id_profissional BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome            VARCHAR(255)                            NOT NULL,
    sobrenome       VARCHAR(255)                            NOT NULL,
    cpf             VARCHAR(255)                            NOT NULL,
    email           VARCHAR(255)                            NOT NULL,
    data_nascimento date,
    data_admissao   date,
    CONSTRAINT pk_profissional PRIMARY KEY (id_profissional)
);

CREATE TABLE profissional_usuario
(
    profissional_id_profissional BIGINT NOT NULL,
    usuario_id_usuario           BIGINT NOT NULL
);

ALTER TABLE profissional
    ADD CONSTRAINT uc_profissional_cpf UNIQUE (cpf);

ALTER TABLE profissional
    ADD CONSTRAINT uc_profissional_email UNIQUE (email);

ALTER TABLE profissional_usuario
    ADD CONSTRAINT uc_profissional_usuario_usuario_id_usuario UNIQUE (usuario_id_usuario);

ALTER TABLE profissional_usuario
    ADD CONSTRAINT fk_prousu_on_profissional FOREIGN KEY (profissional_id_profissional) REFERENCES profissional (id_profissional);

ALTER TABLE profissional_usuario
    ADD CONSTRAINT fk_prousu_on_usuario FOREIGN KEY (usuario_id_usuario) REFERENCES usuario (id_usuario);