CREATE TABLE plano
(
    id_plano         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao        VARCHAR(255)                            NOT NULL,
    vigencia         date                                    NOT NULL,
    preco            DECIMAL                                 NOT NULL,
    quantidade_meses INTEGER                                 NOT NULL,
    CONSTRAINT pk_plano PRIMARY KEY (id_plano)
);

ALTER TABLE plano
    ADD CONSTRAINT uc_plano_descricao UNIQUE (descricao);