CREATE TABLE cliente
(
    id_cliente       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome             VARCHAR(255)                            NOT NULL,
    sobrenome        VARCHAR(255)                            NOT NULL,
    apelido          VARCHAR(255),
    cpf              VARCHAR(255)                            NOT NULL,
    email            VARCHAR(255)                            NOT NULL,
    data_nascimento  date,
    id_plano   BIGINT                                  NOT NULL,
    data_cadastro    date,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente)
);

ALTER TABLE cliente
    ADD CONSTRAINT FK_CLIENTE_ON_PLANO_ID_PLANO FOREIGN KEY (id_plano) REFERENCES plano (id_plano);