CREATE TABLE pagamento
(
    id_pagamento    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_pagamento  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    forma_pagamento VARCHAR(255)                            NOT NULL,
    id_cliente      BIGINT                                  NOT NULL,
    id_plano        BIGINT                                  NOT NULL,
    valor           DECIMAL                                 NOT NULL,
    observacao      VARCHAR(255),
    CONSTRAINT pk_pagamento PRIMARY KEY (id_pagamento)
);

ALTER TABLE pagamento
    ADD CONSTRAINT FK_PAGAMENTO_ON_ID_CLIENTE FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente);

ALTER TABLE pagamento
    ADD CONSTRAINT FK_PAGAMENTO_ON_ID_PLANO FOREIGN KEY (id_plano) REFERENCES plano (id_plano);